# Javascript Node CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test

  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: add github.com to known hosts
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: install gh-pages
          command: sudo npm install -g gh-pages
      - run:
          name: deploy app to gh-pages
          command: gh-pages -d build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: circleci